services:
  frontend:
    container_name: frontend
    build: .
    ports:
      - "3000:3000"
    # command: sh -c "npm i && npm start"
    volumes:
      - './:/usr/frontend'
      - /node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
